# Generated by Django 5.1.2 on 2024-10-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='faculty_id',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
